// Output writers: catalog-index.json, prefix-bucketed enrichment files,
// manifest.json and SOURCES.md. Output is deterministic (sorted keys, sorted
// records) so change-detection diffs are meaningful.

import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

// Bucket a NORAD id into a 1000-wide group: id 25544 → bucket 25. Length-
// independent (handles 5- and 6-digit ids); the client computes the same with
// Math.floor(parseInt(norad,10)/1000).
export function bucketOf(norad) {
  return Math.floor(parseInt(norad, 10) / 1000);
}

// Stable JSON: object keys sorted recursively, so equal data → equal bytes.
function stable(v) {
  if (Array.isArray(v)) return v.map(stable);
  if (v && typeof v === 'object') {
    const o = {};
    for (const k of Object.keys(v).sort()) o[k] = stable(v[k]);
    return o;
  }
  return v;
}
function stringify(v) {
  return JSON.stringify(stable(v), null, 0) + '\n';
}

const byNoradNum = (a, b) => parseInt(a.norad, 10) - parseInt(b.norad, 10);

export async function writeOutputs(dataDir, records, manifest, sourceMeta) {
  const enrichDir = join(dataDir, 'enrichment');
  await mkdir(enrichDir, { recursive: true });

  const all = Array.from(records.values()).sort(byNoradNum);

  // 1. Lean catalogue index for the browse/filter list.
  const index = all.map((r) => ({
    norad: r.norad,
    name: r.name ?? null,
    objectType: r.objectType ?? null,
    country: r.country ?? null,
    opsStatus: r.opsStatus ?? null,
    rcsSize: r.rcsSize ?? null,
    stdMag: r.stdMag ?? null,
    // Present (1) only for constellation-estimated magnitudes, so the browser
    // can mark them; omitted otherwise to keep the index lean.
    ...(r.magSource === 'estimate' ? { magEst: 1 } : {}),
  }));
  await writeFile(join(dataDir, 'catalog-index.json'), stringify(index));

  // 2. Full records, bucketed by NORAD/1000. Clear stale buckets first so a
  //    shrunk catalogue never leaves orphans behind.
  for (const f of await readdir(enrichDir).catch(() => [])) {
    if (f.endsWith('.json')) await rm(join(enrichDir, f));
  }
  const buckets = new Map();
  for (const r of all) {
    const b = bucketOf(r.norad);
    if (!buckets.has(b)) buckets.set(b, {});
    buckets.get(b)[r.norad] = r;
  }
  for (const [b, obj] of [...buckets].sort((a, z) => a[0] - z[0])) {
    await writeFile(join(enrichDir, `${b}.json`), stringify(obj));
  }

  // 3. Manifest — the only place run metadata lives.
  await writeFile(join(dataDir, 'manifest.json'), stringify({
    schemaVersion: 1,
    generatedAt: manifest.generatedAt,
    counts: manifest.counts,
    buckets: buckets.size,
    sources: sourceMeta,
  }));

  return { records: all.length, buckets: buckets.size };
}

// Standalone sky artifact for the observer / sky-dome view. Flat array,
// brightest first, loaded once (NOT NORAD-bucketed) — it's a few hundred rows,
// not thousands of satellites, and shares no key with the enrichment records.
// Written unconditionally so a build with the star source missing/empty still
// leaves a well-formed (empty) file rather than a stale one.
export async function writeStars(dataDir, records, meta) {
  const skyDir = join(dataDir, 'sky');
  await mkdir(skyDir, { recursive: true });
  const stars = Array.from(records.values()).sort((a, b) => a.mag - b.mag);
  await writeFile(join(skyDir, 'stars.json'), stringify({
    schemaVersion: 1,
    generatedAt: meta.generatedAt,
    maxMag: meta.maxMag ?? null,
    stars,
  }));
  return stars.length;
}

// Regenerate the attribution file from each adapter's declared licence.
export async function writeSources(repoRoot, licences) {
  const body = [
    '# Data sources & attribution',
    '',
    'Orbit enriches its satellite catalogue from the sources below. The build',
    'job (`scripts/enrich/`) fetches and normalises them; each field records its',
    'winning source in `_sources` within the enrichment files.',
    '',
    ...licences.map((l) => `- **${l.id}** — ${l.licence}`),
    '',
    '_This file is generated by the enrichment build; edit the adapters, not here._',
    '',
  ].join('\n');
  await writeFile(join(repoRoot, 'SOURCES.md'), body);
}
